
spring:
  datasource:
    url: jdbc:mysql://116.62.25.111/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    username: oa
    password: saoyidiande
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    fliter: stat
server:
  port: 8089
mybatis:
  type-aliases-package: com.demo.pojo
  mapper-locations: classpath:Mapper/*Mapper.xml


logging:
  level:
    com.demo.model.Mapper: debug
